sudo: required
services:
  - docker
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
before_script:
  - npm install -g gulp
script:
  - npm run build
  - npm run test:coveralls
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
